-- SQLite
CREATE TABLE IF NOT EXISTS Cliente (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    cpf TEXT NOT NULL,
    data_nascimento TEXT NOT NULL,
    email TEXT NOT NULL,
    celular TEXT
);

CREATE TABLE IF NOT EXISTS Voo (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    origem TEXT NOT NULL,
    destino TEXT NOT NULL,
    data TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Reserva (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    idCliente INTEGER NOT NULL,
    idVoo INTEGER NOT NULL,
    data TEXT NOT NULL,
    valor REAL NOT NULL,
    FOREIGN KEY (idCliente) REFERENCES Cliente(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (idVoo) REFERENCES Voo(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);